### ISSUE TITLE
In projects, Different Manager shown in Web and App

### ISSUE THREAD

**Issue by ajayrajecb** [EasyCloudConsultants/EasyCloudBooks.Client.Mobile#22]
Scenario : Check when one is relationship manager and one is project manager and both are different person then what app displays in project.

### Result : on Web relationship manager shown
![2019-09-27_14-52-41](https://user-images.githubusercontent.com/46882964/65758652-11d2f680-e137-11e9-92db-b141f33dbc04.png)

### while in App project manager shown
![inapp](https://user-images.githubusercontent.com/46882964/65758673-18fa0480-e137-11e9-92b7-622a71b86e86.png)

**Comment by mitulpanch** [comment]
Web version is staff and  client  version is according to client, Scope is different

**Comment by risipatel** [comment]
If Client relationship manager is there then that means Client is supposed to interact with team via Relationship manager.
Whereas app displays project manager even if Client Relationship manager is there.
