### ISSUE TITLE
Once logged in with one email then App doesn't allows to switch to another.

### ISSUE THREAD

**Issue by risipatel** [EasyCloudConsultants/EasyCloudBooks.Client.Mobile#5]
**After logging in with one id when user logs out from the app and then wants to login with different id as different contact then system doesn't displays option to choose Log in as.
To do that either user might have to remove that google id from his phone or might have to re-install the app.**
![image](https://user-images.githubusercontent.com/46882833/65328057-0467ba80-dbd3-11e9-877a-c2e541d76dc6.png)

**Comment by mitulpanch** [comment]
We can not do anything for this, it is processed by Google
